name: Go Formatter

on:
  push:
  pull_request:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  format:
    name: Format Go Code
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: stable

      - name: Format Go files
        run: |
          gofmt -s -w .
          go mod tidy

      - name: Commit formatting changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "chore: format Go code"
